-- HNSW vector index migration (superseded by 014_fix_hnsw_deferred.sql).
-- Original CREATE INDEX statements failed on fresh databases because pgvector
-- cannot build HNSW on a dimensionless vector column with no data.
-- This migration is now a no-op; the deferred logic lives in 014.
