// pattern: Imperative Shell

import { describe, it, expect, beforeAll, afterEach, afterAll } from 'bun:test';
import { randomUUID } from 'node:crypto';
import { createPostgresProvider } from '../persistence/postgres.ts';
import { createPostgresScheduler } from './postgres-scheduler.ts';
import type { SchedulerRow } from './types.ts';

const DB_CONNECTION_STRING =
  'postgresql://constellation:constellation@localhost:5432/constellation';

let persistence: ReturnType<typeof createPostgresProvider>;
const TEST_OWNER = 'test-owner-' + randomUUID();
let activeScheduler: ReturnType<typeof createPostgresScheduler> | null = null;

async function cleanupTables(): Promise<void> {
  await persistence.query('TRUNCATE TABLE scheduled_tasks CASCADE');
}

describe('PostgreSQL Scheduler', () => {
  beforeAll(async () => {
    persistence = createPostgresProvider({
      url: DB_CONNECTION_STRING,
    });

    await persistence.connect();
    await persistence.runMigrations();
    await cleanupTables();
  });

  afterEach(async () => {
    activeScheduler?.stop();
    activeScheduler = null;
    await cleanupTables();
  });

  afterAll(async () => {
    await persistence.disconnect();
  });

  describe('agent-reflexion.AC4.1: Task persistence across restarts', () => {
    it('schedule() creates a task with correct owner, name, schedule, payload, and computed next_run_at', async () => {
      activeScheduler = createPostgresScheduler(persistence, TEST_OWNER);
      const scheduler = activeScheduler;

      const task = {
        id: 'ignored', // id is generated by schedule()
        name: 'test-task',
        schedule: '0 9 * * *', // Daily at 9 AM
        payload: { action: 'test-action', data: 42 },
      };

      await scheduler.schedule(task);

      const rows = await persistence.query<SchedulerRow>(
        'SELECT * FROM scheduled_tasks WHERE owner = $1 AND name = $2',
        [TEST_OWNER, 'test-task'],
      );

      expect(rows).toHaveLength(1);
      const row = rows[0]!;

      expect(row.owner).toBe(TEST_OWNER);
      expect(row.name).toBe('test-task');
      expect(row.schedule).toBe('0 9 * * *');
      expect(row.payload).toEqual({ action: 'test-action', data: 42 });
      expect(row.next_run_at).toBeTruthy();
      expect(row.next_run_at.getTime()).toBeGreaterThan(Date.now());
      expect(row.cancelled).toBe(false);
      expect(row.last_run_at).toBeNull();
    });

    it('persists tasks across scheduler restarts', async () => {
      activeScheduler = createPostgresScheduler(persistence, TEST_OWNER);
      const scheduler1 = activeScheduler;

      await scheduler1.schedule({
        id: 'ignored',
        name: 'persistent-task',
        schedule: '0 10 * * *',
        payload: { persistent: true },
      });

      const rows1 = await persistence.query<SchedulerRow>(
        'SELECT * FROM scheduled_tasks WHERE owner = $1',
        [TEST_OWNER],
      );
      expect(rows1).toHaveLength(1);

      createPostgresScheduler(persistence, TEST_OWNER);

      const rows2 = await persistence.query<SchedulerRow>(
        'SELECT * FROM scheduled_tasks WHERE owner = $1',
        [TEST_OWNER],
      );

      expect(rows2).toHaveLength(1);
      expect(rows2[0]!.name).toBe('persistent-task');
    });
  });

  describe('agent-reflexion.AC4.2: onDue handler invocation', () => {
    it('fires onDue handler when next_run_at is in the past', async () => {
      activeScheduler = createPostgresScheduler(persistence, TEST_OWNER);
      const scheduler = activeScheduler;

      const task = {
        id: 'ignored',
        name: 'due-task',
        schedule: '0 9 * * *',
        payload: { test: 'payload' },
      };

      await scheduler.schedule(task);

      const rows = await persistence.query<SchedulerRow>(
        'SELECT * FROM scheduled_tasks WHERE owner = $1',
        [TEST_OWNER],
      );
      const taskId = rows[0]!.id;

      await persistence.query(
        'UPDATE scheduled_tasks SET next_run_at = NOW() - INTERVAL \'1 hour\' WHERE id = $1',
        [taskId],
      );

      const handlerCalls: Array<{
        id: string;
        name: string;
        schedule: string;
        payload: Record<string, unknown>;
      }> = [];
      scheduler.onDue((firedTask) => {
        handlerCalls.push(firedTask);
      });

      scheduler.start();
      await Bun.sleep(100);

      expect(handlerCalls).toHaveLength(1);
      const firedTask = handlerCalls[0]!;
      expect(firedTask.id).toBe(taskId);
      expect(firedTask.name).toBe('due-task');
      expect(firedTask.schedule).toBe('0 9 * * *');
      expect(firedTask.payload).toEqual({ test: 'payload' });

      scheduler.stop();
    });

    it('does not fire handler for tasks in the future', async () => {
      activeScheduler = createPostgresScheduler(persistence, TEST_OWNER);
      const scheduler = activeScheduler;

      await scheduler.schedule({
        id: 'ignored',
        name: 'future-task',
        schedule: '0 9 * * *',
        payload: {},
      });

      const handlerCalls: unknown[] = [];
      scheduler.onDue(() => {
        handlerCalls.push('fired');
      });

      scheduler.start();
      await Bun.sleep(100);

      expect(handlerCalls).toHaveLength(0);

      scheduler.stop();
    });
  });

  describe('agent-reflexion.AC4.3: next_run_at recomputation', () => {
    it('recomputes next_run_at after task execution', async () => {
      activeScheduler = createPostgresScheduler(persistence, TEST_OWNER);
      const scheduler = activeScheduler;

      await scheduler.schedule({
        id: 'ignored',
        name: 'recompute-task',
        schedule: '0 9 * * *',
        payload: {},
      });

      const taskRows = await persistence.query<SchedulerRow>(
        'SELECT * FROM scheduled_tasks WHERE owner = $1',
        [TEST_OWNER],
      );
      const taskId = taskRows[0]!.id;

      await persistence.query(
        'UPDATE scheduled_tasks SET next_run_at = NOW() - INTERVAL \'1 hour\' WHERE id = $1',
        [taskId],
      );

      scheduler.onDue(() => {});

      scheduler.start();
      await Bun.sleep(100);

      const updatedRows = await persistence.query<SchedulerRow>(
        'SELECT * FROM scheduled_tasks WHERE id = $1',
        [taskId],
      );

      expect(updatedRows).toHaveLength(1);
      const updated = updatedRows[0]!;

      expect(updated.last_run_at).toBeTruthy();
      expect(updated.last_run_at!.getTime()).toBeLessThanOrEqual(Date.now());

      expect(updated.next_run_at.getTime()).toBeGreaterThan(Date.now());

      scheduler.stop();
    });

    it('marks task as cancelled if cron has no future occurrence', async () => {
      activeScheduler = createPostgresScheduler(persistence, TEST_OWNER);
      const scheduler = activeScheduler;

      await scheduler.schedule({
        id: 'ignored',
        name: 'no-future-task',
        schedule: '0 9 * * *',
        payload: {},
      });

      const taskRows = await persistence.query<SchedulerRow>(
        'SELECT * FROM scheduled_tasks WHERE owner = $1',
        [TEST_OWNER],
      );
      const taskId = taskRows[0]!.id;

      await persistence.query(
        'UPDATE scheduled_tasks SET schedule = $1 WHERE id = $2',
        ['0 9 31 2 *', taskId],
      );

      await persistence.query(
        'UPDATE scheduled_tasks SET next_run_at = NOW() - INTERVAL \'1 hour\' WHERE id = $1',
        [taskId],
      );

      scheduler.onDue(() => {});

      scheduler.start();
      await Bun.sleep(100);

      const updatedRows = await persistence.query<SchedulerRow>(
        'SELECT * FROM scheduled_tasks WHERE id = $1',
        [taskId],
      );

      expect(updatedRows).toHaveLength(1);
      expect(updatedRows[0]!.cancelled).toBe(true);

      scheduler.stop();
    });
  });

  describe('agent-reflexion.AC4.4: Task cancellation', () => {
    it('cancel() sets cancelled = TRUE', async () => {
      activeScheduler = createPostgresScheduler(persistence, TEST_OWNER);
      const scheduler = activeScheduler;

      await scheduler.schedule({
        id: 'ignored',
        name: 'cancellable-task',
        schedule: '0 9 * * *',
        payload: {},
      });

      const taskRows = await persistence.query<SchedulerRow>(
        'SELECT * FROM scheduled_tasks WHERE owner = $1',
        [TEST_OWNER],
      );
      const taskId = taskRows[0]!.id;

      expect(taskRows[0]!.cancelled).toBe(false);

      await scheduler.cancel(taskId);

      const cancelledRows = await persistence.query<SchedulerRow>(
        'SELECT * FROM scheduled_tasks WHERE id = $1',
        [taskId],
      );

      expect(cancelledRows).toHaveLength(1);
      expect(cancelledRows[0]!.cancelled).toBe(true);
    });

    it('does not fire onDue for cancelled tasks', async () => {
      activeScheduler = createPostgresScheduler(persistence, TEST_OWNER);
      const scheduler = activeScheduler;

      await scheduler.schedule({
        id: 'ignored',
        name: 'to-cancel',
        schedule: '0 9 * * *',
        payload: {},
      });

      const taskRows = await persistence.query<SchedulerRow>(
        'SELECT * FROM scheduled_tasks WHERE owner = $1',
        [TEST_OWNER],
      );
      const taskId = taskRows[0]!.id;

      await scheduler.cancel(taskId);

      await persistence.query(
        'UPDATE scheduled_tasks SET next_run_at = NOW() - INTERVAL \'1 hour\' WHERE id = $1',
        [taskId],
      );

      const handlerCalls: unknown[] = [];
      scheduler.onDue(() => {
        handlerCalls.push('fired');
      });

      scheduler.start();
      await Bun.sleep(100);

      expect(handlerCalls).toHaveLength(0);

      scheduler.stop();
    });

    it('is idempotent (cancelling non-existent task succeeds silently)', async () => {
      activeScheduler = createPostgresScheduler(persistence, TEST_OWNER);
      const scheduler = activeScheduler;

      await scheduler.cancel('non-existent-id');

      const rows = await persistence.query<SchedulerRow>(
        'SELECT * FROM scheduled_tasks WHERE owner = $1',
        [TEST_OWNER],
      );

      expect(rows).toHaveLength(0);
    });
  });

  describe('agent-reflexion.AC4.5: Missed-tick recovery', () => {
    it('fires handler for tasks due during downtime on start()', async () => {
      activeScheduler = createPostgresScheduler(persistence, TEST_OWNER);
      const scheduler = activeScheduler;

      await scheduler.schedule({
        id: 'ignored',
        name: 'missed-task',
        schedule: '0 9 * * *',
        payload: { missed: true },
      });

      const taskRows = await persistence.query<SchedulerRow>(
        'SELECT * FROM scheduled_tasks WHERE owner = $1',
        [TEST_OWNER],
      );
      const taskId = taskRows[0]!.id;

      const now = new Date();
      const oneHourAgo = new Date(now.getTime() - 60 * 60 * 1000);
      const twoHoursAgo = new Date(now.getTime() - 2 * 60 * 60 * 1000);

      await persistence.query(
        'UPDATE scheduled_tasks SET next_run_at = $1, last_run_at = $2 WHERE id = $3',
        [oneHourAgo, twoHoursAgo, taskId],
      );

      const handlerCalls: unknown[] = [];
      scheduler.onDue(() => {
        handlerCalls.push('fired');
      });

      scheduler.start();
      await Bun.sleep(100);

      expect(handlerCalls).toHaveLength(1);

      const updatedRows = await persistence.query<SchedulerRow>(
        'SELECT * FROM scheduled_tasks WHERE id = $1',
        [taskId],
      );
      expect(updatedRows[0]!.last_run_at).toBeTruthy();

      scheduler.stop();
    });
  });

  describe('Invalid cron expression handling', () => {
    it('throws error for invalid cron expression', async () => {
      activeScheduler = createPostgresScheduler(persistence, TEST_OWNER);
      const scheduler = activeScheduler;

      const invalidTask = {
        id: 'ignored',
        name: 'invalid',
        schedule: 'not-a-cron-expression',
        payload: {},
      };

      try {
        await scheduler.schedule(invalidTask);
        expect.unreachable('Should have thrown an error');
      } catch (error) {
        expect(error).toBeInstanceOf(Error);
        expect((error as Error).message).toContain('Invalid cron expression');
      }
    });
  });
});
